pub mod resolve_variable;
pub mod resolve_binary;
pub mod apply_bin;
pub mod resolve_special_assignment;
pub mod resolve_func_call;
pub mod call_native_fn;
pub mod resolve_keyword;
pub mod resolve_if;
pub mod resolve_scope;